DROP DATABASE IF EXISTS email;
CREATE DATABASE email;
USE email;

CREATE TABLE message (
id INTEGER(11) AUTO_INCREMENT NOT NULL,
name VARCHAR(50) NOT NULL,
email VARCHAR(50) NOT NULL,
message VARCHAR(255) NOT NULL,
primary key(id)
);

SELECT * FROM message;
